<?xml version="1.0" encoding="utf-8"?><Database Name="Northwind" Class="DataClassesProcDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-I6RMQON\SQLEXPRESS;Initial Catalog=Northwind;Integrated Security=True" SettingsObjectName="LINQsql_m.Properties.Settings" SettingsPropertyName="NorthwindConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.[Ten Most Expensive Products]" Method="Ten_Most_Expensive_Products">
    <ElementType Name="Ten_Most_Expensive_ProductsResult">
      <Column Name="TenMostExpensiveProducts" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>